.TH dl 1 "April 2015"

.SH NAME 
dl \- Draw Line

.SH SYNOPSIS 
dl [flags] [text]

.SH DESCRIPTION
Draws lines with colors, unicode, and export settings.

.SH OPTIONS
.TP 
\-h
--help
.TP
\-v  
--version
.TP 
Colors:
.TP  
\-r  
--red
.TP  
\-g 
--green
.TP
\-b
--blue
.TP
\-y
--yellow
.TP
\-c
--cyan
.TP
\-m
--magenta
.TP
\-k
--black
.TP
\-w
--white
.TP
An uppercase color flag uses the bright version of that color.
.BR
.TP
\-d  --dash dash_symbol
.TP
\-n  --columns number
.TP
\-S  --start
.TP
\-E  --end
.TP
\-N  --center
.TP
text Text to be inserted into the center of a line

.SH ENVIRONMENT 
Not yet implemented.

.SH EXAMPLES
Need to add examples

.SH AUTHOR
Mike Sergio 
www.github.com/michaelsergio/dl
